/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.riso.smartdeviceapp.commonapi;

public class CommonAPIJNI {
  public final static native long new_DirectPrint();
  public final static native void delete_DirectPrint(long jarg1);
  public final static native String DirectPrint_getClassName();
}
