/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.riso.smartdeviceapp.commonapi;

public class DirectPrint {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DirectPrint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DirectPrint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CommonAPIJNI.delete_DirectPrint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DirectPrint() {
    this(CommonAPIJNI.new_DirectPrint(), true);
  }

  public static String getClassName() {
    return CommonAPIJNI.DirectPrint_getClassName();
  }

}
