# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Dev Android Build"
  lane :dev_build do 
    gradle(
        print_command_output: false,
        tasks: ["clean", "build","bundle"]
    )
  end 

  desc "Release Android Build"
  lane :release_build do 
    
    gradle(
        print_command_output: false,
        tasks: ["clean", "build","bundle","assemble"],
        properties: {
          "android.injected.signing.store.file" => ENV["CI_PROJECT_DIR"]+"/Android/storefiles/smartdeviceapp.keystore",
       
          "android.injected.signing.store.password" => ENV["ANDROID_STORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["ANDROID_ALIAS"],
          "android.injected.signing.key.password" => ENV["ANDROID_ALIAS_PASSWORD"],
        }
    )
  end 

  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
